%YAML 1.2
---
support.type.builtin.ts:
  foreground: ${{ colors.chalky }}
  italic: ${{ settings.italic }}
  bold: ${{ settings.bold }}
support.type.builtin.tsx:
  foreground: ${{ colors.chalky }}
  italic: true
support.type.primitive.ts:
  foreground: ${{ colors.chalky }}
  bold: true
support.type.primitive.tsx:
  foreground: ${{ colors.chalky }}
  italic: true
  bold: true
