name: Publish
on:
  push:
    tags:
      - v*.*.*
jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create release
        uses: Roang-zero1/github-create-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-vsce:
    name: Publish to Visual Studio Marketplace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install
        run: npm ci --production
      - name: Publish to Visual Studio Marketplace
        run: npx --no-install vsce publish -p ${{ secrets.vsce_token }}
  publish-github:
    name: Publish to GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install
        run: npm ci --production
      - name: Package extension
        run: npm run package
      - name: Upload extension to release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: "*.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
